spring:
  rabbitmq:
     host: 192.168.88.188
     port: 5672
     username: admin
     password: admin
  datasource:
     url: jdbc:mysql://192.168.88.188:3301/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
     username: root
     password: 123456
  profiles:
    active: redis,mq,redisson,com

#mybatis配置
mybatis-plus:
  mapper-locations: classpath*:mybatis/mapper/*.xml
#  config-location: classpath:mybatis-config.xml


# 测试mq
mq.exchange.queue: zz.queue2
mq.exchange.exchange: zz.exchange2
mq.exchange.routekey: zz.haha2

#系统环境
env: dev
# 测试userId
#userId: 123测试